pluginManagement {
    repositories {
        maven { url = "https://maven.fabricmc.net/" }
        maven { url = "https://maven.terraformersmc.com/releases" }
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode = RepositoriesMode.PREFER_PROJECT
    repositories {
        maven { url = "https://maven.fabricmc.net/" }
        maven { url = "https://maven.terraformersmc.com/releases" }
        mavenCentral()
    }
}

rootProject.name = "Boshys-BTE-Utils"
